/// Flutter icons CustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';
import 'package:flutter_svg/svg.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData arrowRight = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData dashboard = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData delete = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData exit = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData lock = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData menu = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData minimize = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData minus = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData modifiers = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData nacenka = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData percent = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData plus = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData save = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData skidka = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData table = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData userOutline = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData users = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData waiter = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData warning = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData dashboardFill = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData arrowLeft = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData print = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData moon = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData sun = IconData(0xe818, fontFamily: _kFontFam);
  static const String plus_minus = "assets/icones/plus_minus.svg";
  static const String close = "assets/icones/close.svg";
  static const String coin = "assets/icones/coin.svg";
  static const String pracent = "assets/icones/pracent.svg";
  static const String scan = "assets/icones/scaner_search.svg";
   static const String code = "assets/icones/code_search.svg";
  static const String productSearch = "assets/icones/product_search.svg";
  static const String iconLogo = "assets/images/logo.png";
  static const String logout = "assets/icones/logout.svg";
  static const String closeIcon = "assets/icones/closIcon.svg";
  static const String incasVnes = "assets/icones/incasVnes.svg";
  static const String closeChange = "assets/icones/close_change.svg";
  static const String logo_for_dark = "assets/images/logo_for_dark.png";
    static const String notif_error = "assets/icones/notif_error.svg";
        static const String successed = "assets/icones/successed.svg";
}
